a = float (input("give us first number  :"))
b = float (input("give us second number  :"))
c = float (input("give us tird number  :"))
print (int (a), int (b), int(c), sep="*")
print (f'your first number is :{int(a)} and your second number is :{int(b)} and your tird number is :{int(c)}')
print ('your first number is :{} and your second number is :{} and your tird number is :{}' format(int(a), int(b), int(c)))